module "network" {
  source                = "./network"
  VPC_NAME              = var.VPC_NAME
  VPC_CIDR              = var.VPC_CIDR
  PUBLIC_SUBNET_NAME    = var.PUBLIC_SUBNET_NAME
  PUBLIC_SUBNET_CIDR    = var.PUBLIC_SUBNET_CIDR
  PRIVATE_SUBNET_NAME   = var.PRIVATE_SUBNET_NAME
  PRIVATE_SUBNET_CIDR   = var.PRIVATE_SUBNET_CIDR
  INTERNET_GATEWAY_NAME = var.INTERNET_GATEWAY_NAME
  NAT_GATEWAY_NAME      = var.NAT_GATEWAY_NAME
  PUBLIC_RT_NAME        = var.PUBLIC_RT_NAME
  PRIVATE_RT_NAME       = var.PRIVATE_RT_NAME
}